import { Link } from "wouter";
import { useGetDashboardSummary, useListBrands, getGetDashboardSummaryQueryKey, getListBrandsQueryKey } from "@workspace/api-client-react";
import {
  Building2, Megaphone, FileText, PlusCircle, ArrowRight, Sparkles,
  TrendingUp, Clock, BarChart3, Activity, Star
} from "lucide-react";
import { cn } from "@/lib/utils";

function StatusBadge({ status }: { status: string }) {
  const map: Record<string, { label: string; className: string }> = {
    draft: { label: "Draft", className: "bg-muted text-muted-foreground" },
    kit_ready: { label: "Kit Ready", className: "bg-blue-50 text-blue-600 dark:bg-blue-950 dark:text-blue-300" },
    active: { label: "Active", className: "bg-green-50 text-green-600 dark:bg-green-950 dark:text-green-300" },
  };
  const s = map[status] ?? { label: status, className: "bg-muted text-muted-foreground" };
  return (
    <span className={cn("inline-flex items-center px-2 py-0.5 rounded text-[11px] font-medium", s.className)}>
      {s.label}
    </span>
  );
}


export default function Dashboard() {
  const { data: summary, isLoading: summaryLoading } = useGetDashboardSummary({
    query: { queryKey: getGetDashboardSummaryQueryKey() },
  });
  const { data: brands, isLoading: brandsLoading } = useListBrands({
    query: { queryKey: getListBrandsQueryKey() },
  });

  const stats = [
    {
      label: "Total Brands",
      value: summary?.totalBrands ?? 0,
      icon: Building2,
      color: "text-primary",
      bg: "bg-primary/10",
      trend: "+2 this month",
    },
    {
      label: "Campaigns",
      value: summary?.totalCampaigns ?? 0,
      icon: Megaphone,
      color: "text-violet-500",
      bg: "bg-violet-50 dark:bg-violet-950",
      trend: "Active now",
    },
    {
      label: "Social Posts",
      value: summary?.totalPosts ?? 0,
      icon: FileText,
      color: "text-cyan-500",
      bg: "bg-cyan-50 dark:bg-cyan-950",
      trend: "Generated by AI",
    },
    {
      label: "AI Score",
      value: "94%",
      icon: Star,
      color: "text-amber-500",
      bg: "bg-amber-50 dark:bg-amber-950",
      trend: "Brand consistency",
    },
  ];

  const isLoading = summaryLoading || brandsLoading;

  return (
    <div className="px-6 py-8 max-w-7xl mx-auto space-y-8">
      {/* Header */}
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
            <span className="text-xs text-muted-foreground font-medium">AI Agent Active</span>
          </div>
          <h1 className="text-2xl font-bold text-foreground tracking-tight">Command Center</h1>
          <p className="text-sm text-muted-foreground mt-1">Your intelligent brand & marketing platform at a glance.</p>
        </div>
        <div className="flex items-center gap-2 flex-wrap">
          <Link
            href="/analytics"
            className="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-border text-sm font-medium text-muted-foreground hover:text-foreground hover:bg-muted/50 transition-colors"
          >
            <Activity className="w-4 h-4" />
            Analytics
          </Link>
          <Link
            href="/brands/new"
            className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-primary text-primary-foreground text-sm font-medium hover:bg-primary/90 transition-colors"
          >
            <PlusCircle className="w-4 h-4" />
            New Brand
          </Link>
        </div>
      </div>

      {/* Stats grid */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        {stats.map((s) => {
          const Icon = s.icon;
          return (
            <div key={s.label} className="rounded-xl border border-card-border bg-card p-5 space-y-3">
              <div className="flex items-center justify-between">
                <div className={cn("w-9 h-9 rounded-lg flex items-center justify-center", s.bg)}>
                  <Icon className={cn("w-4.5 h-4.5", s.color)} />
                </div>
              </div>
              {isLoading ? (
                <div className="h-7 w-12 bg-muted animate-pulse rounded" />
              ) : (
                <p className="text-2xl font-bold text-foreground tabular-nums">{s.value}</p>
              )}
              <div>
                <p className="text-xs text-muted-foreground font-medium">{s.label}</p>
                <p className="text-[11px] text-muted-foreground/60 mt-0.5">{s.trend}</p>
              </div>
            </div>
          );
        })}
      </div>

      <div className="space-y-4">
        {/* Brand Projects */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h2 className="text-base font-semibold text-foreground flex items-center gap-2">
              <TrendingUp className="w-4 h-4 text-muted-foreground" />
              Brand Projects
            </h2>
            <span className="text-xs text-muted-foreground">{brands?.length ?? 0} total</span>
          </div>

          {isLoading ? (
            <div className="space-y-3">
              {[1, 2, 3].map((i) => (
                <div key={i} className="h-20 rounded-xl bg-muted/50 animate-pulse" />
              ))}
            </div>
          ) : !Array.isArray(brands) || brands.length === 0 ? (
            <div className="rounded-xl border border-dashed border-border bg-muted/20 p-12 text-center">
              <div className="w-14 h-14 rounded-2xl bg-primary/10 flex items-center justify-center mx-auto mb-4">
                <Sparkles className="w-7 h-7 text-primary" />
              </div>
              <h3 className="text-base font-semibold text-foreground mb-1">No brands yet</h3>
              <p className="text-sm text-muted-foreground mb-6 max-w-sm mx-auto">
                Create your first brand and let the AI build a complete visual identity and marketing strategy.
              </p>
              <Link
                href="/brands/new"
                className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg bg-primary text-primary-foreground text-sm font-medium hover:bg-primary/90 transition-colors"
              >
                <PlusCircle className="w-4 h-4" />
                Create your first brand
              </Link>
            </div>
          ) : (
            <div className="space-y-2">
              {brands.map((brand) => (
                <Link
                  key={brand.id}
                  href={`/brands/${brand.id}`}
                  className="flex items-center gap-4 p-4 rounded-xl border border-card-border bg-card hover:bg-muted/30 transition-colors group"
                >
                  {brand.logoUrl ? (
                    <img
                      src={brand.logoUrl}
                      alt={brand.companyName}
                      className="w-10 h-10 rounded-lg object-cover flex-shrink-0"
                    />
                  ) : (
                    <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
                      <Building2 className="w-5 h-5 text-primary" />
                    </div>
                  )}
                  <div className="flex-1 min-w-0">
                    <p className="font-semibold text-sm text-foreground truncate">{brand.companyName}</p>
                    <p className="text-xs text-muted-foreground">{brand.industry}</p>
                  </div>
                  <div className="flex items-center gap-3">
                    <StatusBadge status={brand.status} />
                    <div className="flex items-center gap-1 text-xs text-muted-foreground">
                      <Clock className="w-3.5 h-3.5" />
                      {new Date(brand.createdAt).toLocaleDateString()}
                    </div>
                    <ArrowRight className="w-4 h-4 text-muted-foreground group-hover:text-foreground transition-colors" />
                  </div>
                </Link>
              ))}
            </div>
          )}

          {/* Quick Actions */}
          <div className="grid grid-cols-3 gap-3 pt-2">
            {[
              { href: "/assets", icon: FileText, label: "Asset Library", color: "text-cyan-500", bg: "bg-cyan-50 dark:bg-cyan-950" },
              { href: "/templates", icon: TrendingUp, label: "Templates", color: "text-violet-500", bg: "bg-violet-50 dark:bg-violet-950" },
              { href: "/analytics", icon: BarChart3, label: "Analytics", color: "text-amber-500", bg: "bg-amber-50 dark:bg-amber-950" },
            ].map((qa) => {
              const Icon = qa.icon;
              return (
                <Link
                  key={qa.href}
                  href={qa.href}
                  className="flex flex-col items-center gap-2 p-4 rounded-xl border border-card-border bg-card hover:bg-muted/30 transition-colors text-center group"
                >
                  <div className={cn("w-9 h-9 rounded-lg flex items-center justify-center", qa.bg)}>
                    <Icon className={cn("w-4.5 h-4.5", qa.color)} />
                  </div>
                  <span className="text-xs font-medium text-muted-foreground group-hover:text-foreground transition-colors">{qa.label}</span>
                </Link>
              );
            })}
          </div>
        </div>

      </div>
    </div>
  );
}
